### ISSUE TITLE
Issue with solving for MESP with new feedstock prices in Monte Carlo

### ISSUE THREAD

**Issue by dstew16** [dstew16/BioLocE#8]
Hi Yoel,

I'm working to generate what should be my final datasets for my TEA project with the location-specific feedstock price information I've found, but of course I've run into a bit of an issue.

When working with the `cs_model.py` file in the `incentives` folder, I now get an issue ending with `RuntimeError: minimum tolerance reached; root could not be solved`. This issue only happens when I pass the new feedstock prices. The file works if I use the default price, and each step of using the new prices (i.e., getting the price from the dataframe, setting it for the TEA, solving for MESP, and setting the Monte Carlo distribution of prices) works individually, but whenever I try to use the `evaluate` function in that file for a Monte Carlo analysis, I get this error. (If you want to try this, the file will work if lines 122 and 135 are muted, but not work if they are unmuted)

The only thing that comes to mind as problematic is that all of the new prices are about twice as high as the prices we've been using previously, but I would still expect the solving methods to work. Do you have any ideas for how to resolve this issue? Thanks for taking a look!

**Comment by yoelcortes** [comment]
@dstew16, I can check this out tomorrow, no worries!

**Comment by yoelcortes** [comment]
Done! You'll need to pull biosteam and thermosteam (and maybe bioindustrial-park) to fix the bug. The problem had to do with how the different guesses to solve NPV can give exactly the same number.

Hope this helps!

**Comment by dstew16** [comment]
Yep, works fine now! Thank you!
