### ISSUE TITLE
Best way to adjust TEA for states that assess income tax differently

### ISSUE THREAD

**Issue by dstew16** [dstew16/BioLocE#9]
Hi Yoel,

I've run into another small issue. As I'm generating my state specific TEA results, I've realized that there are 2 states (Ohio and Texas) that assess income tax differently than all other states. They charge comparatively low income tax rates on 'gross receipts', which I believe would be a biorefinery's income before any costs are subtracted.

I'm wondering what the best way to perform TEA for these 2 states would be. The first idea I had was to create a new TEA object with modified income tax formulas, which we could probably come up with relatively quickly (it would be identical to the TEA we use now except for the income tax calculation). I just wanted to check with you to see if you think this is the best approach, or if there's a way we can make use of the TEA objects we have now.

Let me know if you have any ideas. I can provide more info on what the new income tax calculations should look like if you need it. If you want, you can do some quick reading on gross receipts here: https://www.investopedia.com/terms/g/gross-receipts.asp Thanks for your help!

**Comment by yoelcortes** [comment]
Hi Dalton,

Yeah, there are many ways to implement this. Making separate TEA objects is one option, but I think it is easier to make the adjustments as an option in the existing one. Working with too many classes may prove a little difficult down the line. "If" statements are pretty fast and require less coding/refactoring.

I implemented what I think is an option for gross-receipts in 55190bb, which is ultimately the same as gross-sales for the biorefinery (I think). Feel free to undo this commit or make any changes.

Hope this helps,
Thanks!

**Comment by dstew16** [comment]
Thanks, Yoel! I think this looks great! I'll try it out and let you know how it goes.

**Comment by dstew16** [comment]
Unfortunately I'm getting an error. When I try to use the updated TEA, the error message says: 

File "/Users/daltonstewart/anaconda3/lib/python3.7/site-packages/incentives/incentives_tea.py", line 244, in _fill_tax_and_incentives
    tax[:] += state_income_tax_assessed[index]

ValueError: operands could not be broadcast together with shapes (33,) (0,) (33,) 

I tried to do a bit of debugging, but I can't figure out what the three operands with different shapes are. Do you know what it's referring to? Thanks so much for your help! Let me know if you need more info.

**Comment by yoelcortes** [comment]
Ahh, the array shapes do not match (index is a subset of the whole array), you can switch that line to:
```python
tax[index] += state_income_tax_assessed[index]
```

**Comment by dstew16** [comment]
That worked! Glad it was a quick fix! Thanks for your help!!
